-- This migration was originally created before the policies were finalized.
-- The actual RLS policy SQL lives in 20260531150430_add_posts_rls_policies.sql.
-- Keeping this file empty prevents duplicate policy creation on fresh setups.